name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine

    steps:
      - name: Install dependencies
        shell: sh
        run: apk add alpine-sdk git libnl3-dev linux-headers

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Patch
        shell: sh
        run: |
          cd hostap
          cat ../patches/*.patch | patch -tup1

      - name: Compile
        shell: sh
        run: |
          cp config hostap/hostapd/.config
          cd hostap/hostapd
          make -j$(nproc)
          strip hostapd

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: bin-alpine-x86_64
          path: hostap/hostapd/hostapd
          retention-days: 7
